package iotago

// Code generated by go generate; DO NOT EDIT. Check gen/ directory instead.

import (
	"bytes"

	"github.com/iotaledger/hive.go/lo"
	"github.com/iotaledger/hive.go/serializer/v2"
)

type MetadataFeatureEntriesKey string
type MetadataFeatureEntriesValue []byte
type MetadataFeatureEntries map[MetadataFeatureEntriesKey]MetadataFeatureEntriesValue

// MetadataFeature is a feature which simply holds binary data to be freely
// interpreted by higher layer applications.
type MetadataFeature struct {
	Entries MetadataFeatureEntries `serix:""`
}

func (m MetadataFeature) Clone() Feature {
	copiedMap := make(MetadataFeatureEntries)
	for key, value := range m.Entries {
		copiedMap[key] = lo.CopySlice(value)
	}

	return &MetadataFeature{
		Entries: copiedMap,
	}
}

func (m MetadataFeature) StorageScore(_ *StorageScoreStructure, _ StorageScoreFunc) StorageScore {
	return 0
}

func (m MetadataFeature) WorkScore(_ *WorkScoreParameters) (WorkScore, error) {
	return 0, nil
}

func (m MetadataFeature) Equal(other Feature) bool {
	otherFeat, is := other.(*MetadataFeature)
	if !is {
		return false
	}

	if len(m.Entries) != len(otherFeat.Entries) {
		return false
	}

	for key, value := range m.Entries {
		otherValue, exists := otherFeat.Entries[key]
		if !exists {
			return false
		}

		if !bytes.Equal(value, otherValue) {
			return false
		}
	}

	return true
}

func (m MetadataFeature) Type() FeatureType {
	return FeatureMetadata
}

func (m MetadataFeature) mapSize() int {
	var size int

	// Map Length
	size += serializer.SmallTypeDenotationByteSize
	for key, value := range m.Entries {
		// Key Length + Key + Value Length + Value
		size += serializer.SmallTypeDenotationByteSize + len(key) + serializer.UInt16ByteSize + len(value)
	}

	return size
}

func (m MetadataFeature) Size() int {
	// FeatureType + Entries
	return serializer.SmallTypeDenotationByteSize + m.mapSize()
}
