package mam_test

import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	"github.com/pkg/errors"

	"github.com/iotaledger/iota.go/api"
	"github.com/iotaledger/iota.go/bundle"
	"github.com/iotaledger/iota.go/consts"
	mam "github.com/iotaledger/iota.go/mam/v1"
	"github.com/iotaledger/iota.go/trinary"
)

var _ = Describe("Transmitter", func() {

	Context("SetMode", func() {

		It("Should set the mode to private", func() {
			transmitter := mam.NewTransmitter(newFakeAPI(), "seed", 9, consts.SecurityLevelLow)

			err := transmitter.SetMode(mam.ChannelModePrivate, "")

			Expect(err).NotTo(HaveOccurred())
			Expect(transmitter.Mode()).To(Equal(mam.ChannelModePrivate))
		})

		It("Should set the mode to restricted", func() {
			transmitter := mam.NewTransmitter(newFakeAPI(), "seed", 9, consts.SecurityLevelLow)

			err := transmitter.SetMode(mam.ChannelModeRestricted, "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")

			Expect(err).NotTo(HaveOccurred())
			Expect(transmitter.Mode()).To(Equal(mam.ChannelModeRestricted))
			Expect(transmitter.SideKey()).To(Equal(trinary.Trytes("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")))
		})

		It("Should error on undefined mode", func() {
			transmitter := mam.NewTransmitter(newFakeAPI(), "seed", 9, consts.SecurityLevelLow)

			err := transmitter.SetMode("555", "")

			Expect(errors.Cause(err)).To(Equal(mam.ErrUnknownChannelMode))
			Expect(transmitter.Mode()).To(Equal(mam.ChannelModePublic))
			Expect(transmitter.SideKey()).To(Equal("999999999999999999999999999999999999999999999999999999999999999999999999999999999"))
		})

		It("Should error on missing side key in restricted mode", func() {
			transmitter := mam.NewTransmitter(newFakeAPI(), "seed", 9, consts.SecurityLevelLow)

			err := transmitter.SetMode(mam.ChannelModeRestricted, "")

			Expect(errors.Cause(err)).To(Equal(mam.ErrNoSideKey))
			Expect(transmitter.Mode()).To(Equal(mam.ChannelModePublic))
			Expect(transmitter.SideKey()).To(Equal("999999999999999999999999999999999999999999999999999999999999999999999999999999999"))
		})

	})

	Context("Transmit", func() {

		const seed = "TX9XRR9SRCOBMTYDTMKNEIJCSZIMEUPWCNLC9DPDZKKAEMEFVSTEVUFTRUZXEHLULEIYJIEOWIC9STAHW"

		It("Should transmit the given message to a public Channel", func() {
			fakeAPI := newFakeAPI()
			fakeAPI.prepareTransfers = func(address trinary.Trytes, transfers bundle.Transfers, opts api.PrepareTransfersOptions) ([]trinary.Trytes, error) {
				Expect(address).To(Equal("999999999999999999999999999999999999999999999999999999999999999999999999999999999"))
				Expect(transfers).To(Equal(bundle.Transfers{bundle.Transfer{
					Address: "YKOLXUAMTJGGIVPEWHUCSKKJWIY9PWEFABXYHAWDBTMOPKWNXOOQCKNHADSZP9SOSDFEOXPVTWUWFDQNHJXGHIWKOA",
					Value:   0,
					Message: "AZBCERWNZGTGNPUJYARSZHHYKJYXVRWNZODXYRP9TQVT9XX9MMQIDEJUFWNQGTTIMAMENDXVQYHSUVSBXGRAGYSYMFQQTKBKBBNTPABQVVUIYFAQYZGYQLGALVCJCSFNRRXUEODCO9DXHHNMITGJPLISKXXMTRLGRWDTQMHBXZPRWUCPIJEBPWVERLRNGCZPGERXWVKFLCDSZDQ9WQZIYY9MZHRRUJ9EACMREZSZYPMGQV9DUBFTAJEFPCDKWGQTANVYMIJIJHZGMWFCNCBUIXHXG9CTLDTZBSMBWEHNITUOABCWWCOEPAKRFOSZLGTFRNUFKCYOEPKFUSZQPFYODAEJRSNKAUOOPXPBWNXASWXDLMNCFEQWXDQBPKWIZBXNWBHCKTCUPERYDESMGOEZYUODWMHENRWMVKQEQ9AEQPNAFLNKZUMXMQFLGDZBNVQDZCAGQUFCFFCAFYUVNKQLTAO9BTSOIQ9IQLEAWFYACSNEIYVYWNVKCGCKZNGPLXTDNE9PKJBTXXQBDBKH9ICLBUVDVIGXUVVCSCVSLBKVRXBCJHJCRKEYNHSPXIYMWEIWQAIMTYWLOZQTBQNEXFWUOAOJ9LMBXSQQA9DCUOWOGW9JQYWXIVULMDLFVAFPYE9JGRJQLNQTOYNPK9JSB9BERTEICKVMXMLNNOCHTKVACIKEXUXZTQXGTXQMEB9SLDTOK9IFLRXYSKAFTCZVLPR9ECQVNQN9LWYRD9XLYPCKNBBCIJKCWUVGWMXMFOJLVONBKQGIISFWXAOHGUOWCM9YTCUKXKIEO9PCRBPMIPTQXQCLWMWGJHQJMAZBVHIOS9CZBAIGBX9VEKWGEQSMZVBCZNTKNJG9FEPSNLNYAVXTHLVHDTXGJCBRAXGWKBUPIGMRGFOUYFCLUXNNDDUYTFJPHTZYFUNTZXRJRTNSFYQHBSGRJPAEPFIEQJPYXKUXOUCQOXLPKRDJWAKCGWRWGJGWCOUMDDBCTVVOPQQYQOIIQIBKGMBVBPDFKNJVXVPSMZWVWXPWLUZPSXOEGTBXKJTG9ORUJUSMZXFDMMZWYRNMKGTBLXIPHVW9BSDR9LOWGSBHHBUOSZYLJJDTNJKZQWYMNCCMIVLITMFWXAWWHDCOWBTVCOGLTBILLT9KLHECWIGZVAVR99BJEMTXJRXGLXAZYHIGQOJEPMDVYAVSAPQU9JMSIXKISVTRIEI9KM9UGZKBSRLEGZU9UTJNXQRHTXZNAUDA9DFYPWEFDOOMTZICIXGIJELIUNRHSUVJJQJITOOFBFCPQSLKQKNASCTKIPGJQHVGJWETMQGUVJBISTVXNS9BLGRUWNKZQKUPSFOLO9IJQNDLXVVNZH9NRIYKJGPRJZACHECFQSQXMSGKMSTRRAFJWJJBFZCQAOBITPTMLTVLFAGBBZOYEXDFKWBJNXLUUIOSDWNLWQWUXNXOELSHBVMIMHUOPLJLNFBOQ9VPBXRRNHHEKUHNDLZ9GZZRKEXNGMCXSOPZKEUBHYNTTIHIGHDLBLSCGEQHLWKGHDKJTPXYPYNDWNSJOKKKPAUBDTVLMYBT9ITCIH9TJOPTICXTYQSFTHYX9NCZGM9TOBJLEMIVI9EPJAKKRYSDPSXLHQDWJGHJZFTWXVFVZGJKGGMYJHCW9XLFEN9UUYUUCJGEZIQVT9HKXOSBFINKEV9LWTXDDFDIG9YPWPQODFXHSGNIOBFDROPEJZZECPKOAVXVECWABNPWMQSXYSCJALKMF9HUQXAPWTEXHEJ9EQPZZKCUUBYZSNYGBL9JLIRJNZSVVYUGSVTYGUKQDQNCJFM9L9GW9XKIUGAHDUSAFW9ZURVLYGXWHRLLAKHHDRDF9BVTSNNTRJBPDAUWWFKYAHHUUFCQEEPNVPRFPDAOAZSOXKOBYXQIXER9ZH9JKUTAWAAASZ9NBXNEDSYXGARIMOEOMTENPOVGCZTPQLPAYWHUYOFQKUMMYXKTRYCESVPDUJMVDMVPCXC9GYQ9FSNDQYPDIZJZPMRBXUSKOSDDENXFWMQMELOYSFT9GAPEYRUMHRHNBNJUAIZDUOZPVIFBEMVWXDUPTQQWEQIZTVMOKGXIHACDFFRPUX9CZYLKOAVJFQMJZ9YDLSFFSQAJANI9XSGERSUIFTMQ9AZXHGJGKIGLSXBFZMQVQ9XBOHEQJAYDJBZVIZGSAAUHX9ESEDALVQKHRYCPFEAWBQVTAUBQOANWPFYHKGVQKVOYJQFIYSLRAZPLZJLDZXMYRBN9WTYTOZKHSAAIOFVBITRHRMPXNZXZYEVMKOXDMASIBMQEFBAWISR99IVOUDJFTFENZ",
					Tag:     "",
				}}))
				return []trinary.Trytes{"TRYTES"}, nil
			}
			fakeAPI.sendTrytes = func(trytes []trinary.Trytes, depth uint64, mwm uint64, references ...trinary.Hash) (bundle.Bundle, error) {
				Expect(trytes).To(Equal([]trinary.Trytes{"TRYTES"}))
				Expect(depth).To(Equal(uint64(3)))
				Expect(mwm).To(Equal(uint64(9)))
				Expect(references).To(Equal(([]trinary.Hash)(nil)))
				return bundle.Bundle{}, nil
			}
			transmitter := mam.NewTransmitter(fakeAPI, seed, 9, consts.SecurityLevelLow)

			err := transmitter.SetMode(mam.ChannelModePublic, "")
			Expect(err).NotTo(HaveOccurred())

			root, err := transmitter.Transmit("Hello!")
			Expect(err).NotTo(HaveOccurred())
			Expect(root).To(Equal("YKOLXUAMTJGGIVPEWHUCSKKJWIY9PWEFABXYHAWDBTMOPKWNXOOQCKNHADSZP9SOSDFEOXPVTWUWFDQNH"))
		})

		It("Should transmit the given message to a private Channel", func() {
			fakeAPI := newFakeAPI()
			fakeAPI.prepareTransfers = func(address trinary.Trytes, transfers bundle.Transfers, opts api.PrepareTransfersOptions) ([]trinary.Trytes, error) {
				Expect(address).To(Equal("999999999999999999999999999999999999999999999999999999999999999999999999999999999"))
				Expect(transfers).To(Equal(bundle.Transfers{bundle.Transfer{
					Address: "VSGBERKCRZXVDYNHBYCBTEZHQSPJSJEAXSFFBPMNSLENOMGDPUDYXMULBVLUDGROBT9PUSNTMSDQH9WDABDYPTSACC",
					Value:   0,
					Message: "AZBCERWNZGTGNPUJYARSZHHYKJYXVRWNZODXYRP9TQVT9XX9MMQIDEJUFWNQGTTIMAMENDXVQYHSUVSBXGRAGYSYMFQQTKBKBBNTPABQVVUIYFAQYZGYQLGALVCJCSFNRRXUEODCO9DXHHNMITGJPLISKXXMTRLGRWDTQMHBXZPRWUCPIJEBPWVERLRNGCZPGERXWVKFLCDSZDQ9WQZIYY9MZHRRUJ9EACMREZSZYPMGQV9DUBFTAJEFPCDKWGQTANVYMIJIJHZGMWFCNCBUIXHXG9CTLDTZBSMBWEHNITUOABCWWCOEPAKRFOSZLGTFRNUFKCYOEPKFUSZQPFYODAEJRSNKAUOOPXPBWNXASWXDLMNCFEQWXDQBPKWIZBXNWBHCKTCUPERYDESMGOEZYUODWMHENRWMVKQEQ9AEQPNAFLNKZUMXMQFLGDZBNVQDZCAGQUFCFFCAFYUVNKQLTAO9BTSOIQ9IQLEAWFYACSNEIYVYWNVKCGCKZNGPLXTDNE9PKJBTXXQBDBKH9ICLBUVDVIGXUVVCSCVSLBKVRXBCJHJCRKEYNHSPXIYMWEIWQAIMTYWLOZQTBQNEXFWUOAOJ9LMBXSQQA9DCUOWOGW9JQYWXIVULMDLFVAFPYE9JGRJQLNQTOYNPK9JSB9BERTEICKVMXMLNNOCHTKVACIKEXUXZTQXGTXQMEB9SLDTOK9IFLRXYSKAFTCZVLPR9ECQVNQN9LWYRD9XLYPCKNBBCIJKCWUVGWMXMFOJLVONBKQGIISFWXAOHGUOWCM9YTCUKXKIEO9PCRBPMIPTQXQCLWMWGJHQJMAZBVHIOS9CZBAIGBX9VEKWGEQSMZVBCZNTKNJG9FEPSNLNYAVXTHLVHDTXGJCBRAXGWKBUPIGMRGFOUYFCLUXNNDDUYTFJPHTZYFUNTZXRJRTNSFYQHBSGRJPAEPFIEQJPYXKUXOUCQOXLPKRDJWAKCGWRWGJGWCOUMDDBCTVVOPQQYQOIIQIBKGMBVBPDFKNJVXVPSMZWVWXPWLUZPSXOEGTBXKJTG9ORUJUSMZXFDMMZWYRNMKGTBLXIPHVW9BSDR9LOWGSBHHBUOSZYLJJDTNJKZQWYMNCCMIVLITMFWXAWWHDCOWBTVCOGLTBILLT9KLHECWIGZVAVR99BJEMTXJRXGLXAZYHIGQOJEPMDVYAVSAPQU9JMSIXKISVTRIEI9KM9UGZKBSRLEGZU9UTJNXQRHTXZNAUDA9DFYPWEFDOOMTZICIXGIJELIUNRHSUVJJQJITOOFBFCPQSLKQKNASCTKIPGJQHVGJWETMQGUVJBISTVXNS9BLGRUWNKZQKUPSFOLO9IJQNDLXVVNZH9NRIYKJGPRJZACHECFQSQXMSGKMSTRRAFJWJJBFZCQAOBITPTMLTVLFAGBBZOYEXDFKWBJNXLUUIOSDWNLWQWUXNXOELSHBVMIMHUOPLJLNFBOQ9VPBXRRNHHEKUHNDLZ9GZZRKEXNGMCXSOPZKEUBHYNTTIHIGHDLBLSCGEQHLWKGHDKJTPXYPYNDWNSJOKKKPAUBDTVLMYBT9ITCIH9TJOPTICXTYQSFTHYX9NCZGM9TOBJLEMIVI9EPJAKKRYSDPSXLHQDWJGHJZFTWXVFVZGJKGGMYJHCW9XLFEN9UUYUUCJGEZIQVT9HKXOSBFINKEV9LWTXDDFDIG9YPWPQODFXHSGNIOBFDROPEJZZECPKOAVXVECWABNPWMQSXYSCJALKMF9HUQXAPWTEXHEJ9EQPZZKCUUBYZSNYGBL9JLIRJNZSVVYUGSVTYGUKQDQNCJFM9L9GW9XKIUGAHDUSAFW9ZURVLYGXWHRLLAKHHDRDF9BVTSNNTRJBPDAUWWFKYAHHUUFCQEEPNVPRFPDAOAZSOXKOBYXQIXER9ZH9JKUTAWAAASZ9NBXNEDSYXGARIMOEOMTENPOVGCZTPQLPAYWHUYOFQKUMMYXKTRYCESVPDUJMVDMVPCXC9GYQ9FSNDQYPDIZJZPMRBXUSKOSDDENXFWMQMELOYSFT9GAPEYRUMHRHNBNJUAIZDUOZPVIFBEMVWXDUPTQQWEQIZTVMOKGXIHACDFFRPUX9CZYLKOAVJFQMJZ9YDLSFFSQAJANI9XSGERSUIFTMQ9AZXHGJGKIGLSXBFZMQVQ9XBOHEQJAYDJBZVIZGSAAUHX9ESEDALVQKHRYCPFEAWBQVTAUBQOANWPFYHKGVQKVOYJQFIYSLRAZPLZJLDZXMYRBN9WTYTOZKHSAAIOFVBITRHRMPXNZXZYEVMKOXDMASIBMQEFBAWISR99IVOUDJFTFENZ",
					Tag:     "",
				}}))
				return []trinary.Trytes{"TRYTES"}, nil
			}
			fakeAPI.sendTrytes = func(trytes []trinary.Trytes, depth uint64, mwm uint64, references ...trinary.Hash) (bundle.Bundle, error) {
				Expect(trytes).To(Equal([]trinary.Trytes{"TRYTES"}))
				Expect(depth).To(Equal(uint64(3)))
				Expect(mwm).To(Equal(uint64(9)))
				Expect(references).To(Equal(([]trinary.Hash)(nil)))
				return bundle.Bundle{}, nil
			}
			transmitter := mam.NewTransmitter(fakeAPI, seed, 9, consts.SecurityLevelLow)

			err := transmitter.SetMode(mam.ChannelModePrivate, "")
			Expect(err).NotTo(HaveOccurred())

			root, err := transmitter.Transmit("Hello!")
			Expect(err).NotTo(HaveOccurred())
			Expect(root).To(Equal("YKOLXUAMTJGGIVPEWHUCSKKJWIY9PWEFABXYHAWDBTMOPKWNXOOQCKNHADSZP9SOSDFEOXPVTWUWFDQNH"))
		})

		It("Should transmit the given message to a restricted Channel", func() {
			fakeAPI := newFakeAPI()
			fakeAPI.prepareTransfers = func(address trinary.Trytes, transfers bundle.Transfers, opts api.PrepareTransfersOptions) ([]trinary.Trytes, error) {
				Expect(address).To(Equal("999999999999999999999999999999999999999999999999999999999999999999999999999999999"))
				Expect(transfers).To(Equal(bundle.Transfers{bundle.Transfer{
					Address: "YTGYFFZB9IGSHRGYCXPFWCVOWVJMPSTT9BURCEVJUQVIPYRJCVTMWIA9STGLMVHDDAEVQQNW9FIADFPKXCCERTUNDD",
					Value:   0,
					Message: "AZBCLPZ9LZJ9GWQKKSXALILYNQLPNIKRLYXXCXRJDWPDJBLXEFJLIDQLNZNAX9URKQXWDOAQDIPTPAFVFDJCMD9QURLPTUJJEDAAMFDLOLT9LBKIPLATILWBQXMPWL9UAZEWJKOPYAHINJMGIOUEUWOXTAIMGNGJDUXSJLWWLFSRSQDZUIPTXVBXJLMFIUMKNREUQJMLQMMRZSEFTUHMPATPEOLTKYRPCS9DSIUZAAVQVGRCEBMDHYGWS9YUXLBVPHDALLTINKUJQUHUVQHXHHSTAUQNVSIAFMMKZUA9SRFQEBJC9WHCFTILSJMKQLIMUHRCNYIFZVFZQMR9WRILPXCTQUPAZSZ9NZRAAS99SMGISWNNCVHWVTUFHBKWDUOGMIHXFRM9LDEWQ9FMQA9QPCEKSOPIMIBESE9NIDBFPEBQJGHTOZTOOOIBDMNXBNFFITLLPOG99UERZFBLGEPDZXMLZWOTVGVGXXMPBICFMAKVHMQSNBWHBIRXQOTONOHKDJFGFXWITVNTLGUKSVDECQISTFCRLOSWZYPOYNKDVSVDRNU9XLBOXOCMWUGBCDWH9YETUXPZHOWECWTZEKRBUEVQMRLZWIOSNTS9QJOBXLUIXXDZZHJMLODRFTBLWFOPIGXTMMNZGUHQTKRRSVOH9EG9SBZIKZHNHSOQBKJIURFUFKROIVLSJDMAOWQTCHJXKSIAXSYLXWTSMJEXGXOFINSNKBFWITLMMIFKRP9LKIBHEBTUUZHNKSIHBGBPC9G9CA9KEZ9KAAGIL9BN9ARKYQQKNAIYNEOYVZVTKXKXMUBDJHYUEVDMFTVFQNJVRBIXMXYKGTBHLETYUUTUR9SUTQVD9GV9FHZSPBBP9LT9MCRUBYHWBKSWCVW9RGWPRSHJYLHYHUJMBTWVMUHZFLKQSDDXRJWMZAVUUS9KREIGLFQIUINCHJYPCRLSJYKLEMIJYLUMPJPUYHNEIWQVIOKIALOFUUGXQWTUVVOMCKDBHDGOYMGAVRRQ9RTRDYMBSAPR9NULXKZITOVAZOHUA9JLSLGYXWATXMM9ZWPRZUPWNGKNEORFQJHAHQXSKWBSEEIHTBDKRPRQZVGGF9U9GBPSKXKRHUQZDULHSUXSXFTLNMAZUQFSNTVLFPCLEBYZMDUJQPN9NOHXNEGBWYYUPUPHANB9CBXBLHZABCIPYQRRKYVRJVJK9WJIPXFYTLAXKNPRCJVVUGRTIYUSQSMPHUJQ9NIZCLIDKAWLEPJCJTXGXBLGHFWMDSRDIVWUTUDNUYVEZJFIURPV9GESCMPBYJTRXVWWDWCE9QTGKLAEN9Z9AESODMDKPEWRKKVKYBVPVY9MPWCMVEPSZNGRYGZOAHCIJRJZBFNZLFPXUVZVBJBF9NZOOFFXFQSMHDAYUOVTHGJTXHPUXAHHJPLOTCQGDCCRL9SKRE9FMKBC9OQWLHIONQBXTMPRTARSMDLPTVUSGSGGHYWIQ9QCOLUCQGWVQNRMLVEQZRJPSSVJGENAGD9NOGYTWVMGXEDPTIFDRFOOOZHRAZULNFATXQFGNHVOGKCJNRNROEANTZNCVALWXEI9ZDIHOIJBQBBXYPSIMPBPQJCSZUHQHSPBDJM9VLQTCDQLVZTMZJVHVFEKORFVFOVBVJBMTAFBFEIFBUKLYNMOWVVXHLSFVHAV9AVFGDHBXTPOFEKFIZNSHRPERMNARNORHVVDRGR9ZCIMSXYHHFVE9ANGCZKLQDMWQNL9JXWPVLBVGLGECEZKFPZZPWILW9QRNZQEVSMUVODVSVQGUJXSUNFDHNLLIUSJNSVQHYUDSXWBHQZWISMSJTQKAUJDEVYFMJBNYDUFSIUMQJFOENOQXKFZPEPMEPCVNZWAUE9IMENUUOWJEVMZXA9MZYLCOZHNIKSMGL9VARQ9EOLOSGSKSKWDWWWNEPQJEMNLPHRHRMHY9FXUBPIILKPPIYHSUVFAZRPTGGPGVWFKYFHNUYYBSKFBCAKFZMFHMVJYDFUVDXYTCUSOZY9RQWDYWGZCAISGVAUWPLLLBM9FGOSFYVJT9MAAPYGIWZMVHTF9ZXFLOFEKFGNRLCPIAVQQAPCVDVGSVRNU9GHJZFDTSNTMEZCJEMUXEQWHXGKQIAORTKFMHIDXFLVBXKGWAUKIZKKCMTFTTDVWEBXEWQ9YEOLWLNASIFLSUKCCN9HQLVSBVFULJWQKSVYALVDOILT9YHTUDFJHMHIVXFOLHIVTSFWEVNAFBVOUZLRZJNVMMJEBLWFYNTVGZCJAEIGNGKVNBBKAPIGTNKKNBBRTXNFUVAPHRVBIQYIOKWRNBJYC9",
					Tag:     "",
				}}))
				return []trinary.Trytes{"TRYTES"}, nil
			}
			fakeAPI.sendTrytes = func(trytes []trinary.Trytes, depth uint64, mwm uint64, references ...trinary.Hash) (bundle.Bundle, error) {
				Expect(trytes).To(Equal([]trinary.Trytes{"TRYTES"}))
				Expect(depth).To(Equal(uint64(3)))
				Expect(mwm).To(Equal(uint64(9)))
				Expect(references).To(Equal(([]trinary.Hash)(nil)))
				return bundle.Bundle{}, nil
			}
			transmitter := mam.NewTransmitter(fakeAPI, seed, 9, consts.SecurityLevelLow)

			err := transmitter.SetMode(mam.ChannelModeRestricted, "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
			Expect(err).NotTo(HaveOccurred())

			root, err := transmitter.Transmit("Hello!")
			Expect(err).NotTo(HaveOccurred())
			Expect(root).To(Equal("YKOLXUAMTJGGIVPEWHUCSKKJWIY9PWEFABXYHAWDBTMOPKWNXOOQCKNHADSZP9SOSDFEOXPVTWUWFDQNH"))
		})

	})

})
