package consts

import "github.com/pkg/errors"

var (
	ErrNonOKStatusCodeFromAPIRequest = errors.New("received non ok status from backend")
	ErrUnknownErrorFromAPIRequest    = errors.New("received unknown error from backend")
	ErrInvalidSettingsType = errors.New("incompatible settings type supplied")
	ErrSettingsNil = errors.New("settings must not be nil")
)

var (
	ErrInconsistentSubtangle = errors.New("inconsistent subtangle")
)

// invalid inputs
var (
	ErrInvalidSqueezeLength         = errors.New("squeeze length must be a multiple of 243")
	ErrInvalidTritsLength           = errors.New("invalid trits length")
	ErrInvalidTritConversionInput   = errors.New("invalid conversion input. Expected trits as uint8 slice")
	ErrInvalidTryteConversionInput  = errors.New("invalid conversion input. Expected trytes string or integer")
	ErrInvalidBytesLength           = errors.New("invalid bytes length")
	ErrInsufficientBalance          = errors.New("insufficient balance")
	ErrInvalidAddress               = errors.New("invalid address")
	ErrInvalidRemainderAddress      = errors.New("invalid remainder address")
	ErrInvalidBranchTransaction     = errors.New("invalid branch transaction")
	ErrInvalidBundle                = errors.New("invalid bundle")
	ErrInvalidBundleHash            = errors.New("invalid bundle hash")
	ErrInvalidSignature             = errors.New("invalid signature")
	ErrInvalidChecksum              = errors.New("invalid checksum")
	ErrInvalidCommand               = errors.New("invalid command format")
	ErrInvalidDepth                 = errors.New("invalid depth")
	ErrInvalidHash                  = errors.New("invalid hash")
	ErrInvalidIndex                 = errors.New("invalid index option")
	ErrInvalidTotalOption           = errors.New("invalid total option")
	ErrInvalidInput                 = errors.New("invalid input")
	ErrInvalidKey                   = errors.New("invalid key value")
	ErrInvalidMinWeightMagnitude    = errors.New("invalid min weight magnitude")
	ErrInvalidSearchKey             = errors.New("invalid search key")
	ErrInvalidSecurityLevel         = errors.New("invalid security option")
	ErrInvalidSecurityOption        = errors.New("invalid security option")
	ErrInvalidSeed                  = errors.New("invalid seed")
	ErrInvalidStartEndOptions       = errors.New("invalid end option")
	ErrInvalidStartOption           = errors.New("invalid start option")
	ErrInvalidTag                   = errors.New("invalid tag")
	ErrInvalidTransaction           = errors.New("invalid transaction")
	ErrInvalidTransactionTrytes     = errors.New("invalid transaction trytes")
	ErrInvalidAttachedTrytes        = errors.New("invalid attached trytes")
	ErrInvalidTransactionHash       = errors.New("invalid transaction hash")
	ErrInvalidTailTransaction       = errors.New("invalid tail transaction")
	ErrInvalidThreshold             = errors.New("invalid threshold option")
	ErrInvalidTransfer              = errors.New("invalid transfer object")
	ErrInvalidTrunkTransaction      = errors.New("invalid trunk transaction")
	ErrInvalidReferenceHash         = errors.New("invalid reference hash")
	ErrInvalidTrytes                = errors.New("invalid trytes")
	ErrInvalidTrit                  = errors.New("invalid trit")
	ErrInvalidURI                   = errors.New("invalid uri")
	ErrInvalidASCIIInput            = errors.New("conversion to trytes requires type of input to be encoded in ascii")
	ErrInvalidOddLength             = errors.New("conversion from trytes requires length of trytes to be even")
	ErrInvalidTryteEncodedJSON      = errors.New("invalid tryte encoded JSON message")
	ErrNotInt                       = errors.New("one of the inputs is not integer")
	ErrSendingBackToInputs          = errors.New("one of the transaction inputs is used as output")
	ErrInvalidTransactionsToApprove = errors.New("invalid transactions to approve")
	ErrNoInputs                     = errors.New("could not find any available inputs")
	ErrInconsistentTransaction      = errors.New("transaction is inconsistent")
)
